site_name: Proxima
repo_name: in03/proxima
repo_url: https://github.com/in03/proxima

theme:
  name: material
  logo: images/proxima_icon.svg
  favicon: images/proxima_icon.svg
  icon:
    repo: fontawesome/brands/git-alt

  custom_dir: docs/overrides

  nav:
  - Code Reference: reference/poet


  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

  nav:
    - "My page": test.md

  plugins:
  - tags
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          rendering:
            show_source: true

  watch:
    - src/proxima

  - git-revision-date-localized:
      enable_creation_date: true
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index


extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/in03
    - icon: fontawesome/brands/linkedin
      link: https://au.linkedin.com/in/caleb-trevatt-16217b102
copyright: Copyright &copy; 2019 - 2022 Caleb Trevatt

markdown_extensions:
  - admonition
  - codehilite
  - termynal
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true

extra_css:
- css/code_select.css